"""Add created_at and updated_at fields

Revision ID: 632b6b4e725f
Revises: f08adfc4bd70
Create Date: 2024-04-28 05:59:22.067321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '632b6b4e725f'
down_revision: Union[str, None] = 'f08adfc4bd70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seasons', sa.Column('created_at', sa.DateTime(), nullable=True,server_default=sa.text("CURRENT_TIMESTAMP")))
    op.add_column('seasons', sa.Column('updated_at', sa.DateTime(), nullable=True,server_default=sa.text("CURRENT_TIMESTAMP")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seasons', 'updated_at')
    op.drop_column('seasons', 'created_at')
    # ### end Alembic commands ###
