"""added public id

Revision ID: 7f22c2c86e59
Revises: 4486d5dd0ae8
Create Date: 2024-04-14 23:37:05.748391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f22c2c86e59'
down_revision: Union[str, None] = '4486d5dd0ae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seasons', sa.Column('cloudPublicId', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seasons', 'cloudPublicId')
    # ### end Alembic commands ###
