"""added public id

Revision ID: b0163f780829
Revises: 7f22c2c86e59
Create Date: 2024-04-15 09:54:45.858074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0163f780829'
down_revision: Union[str, None] = '7f22c2c86e59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seasons', sa.Column('fixtures', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seasons', 'fixtures')
    # ### end Alembic commands ###
