"""added no of visits

Revision ID: f08adfc4bd70
Revises: bc581a547bdb
Create Date: 2024-04-15 15:41:10.180734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f08adfc4bd70'
down_revision: Union[str, None] = 'bc581a547bdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seasons', sa.Column('noOfVisits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seasons', 'noOfVisits')
    # ### end Alembic commands ###
